### ISSUE TITLE
Admin can create, design and send event invitation

### ISSUE THREAD

**Issue by marysaray** [marysaray/PortfolioProject#1]
Admin should have full CRUD functionality for events.

- [ ] Add Admin Role
- [ ] Admin can Create Event
- [ ] Admin can Edit Event
- [ ] Admin can Delete Event
- [ ] Admin have a landing page for all Events
- [ ] Only Admin can Edit/Delete/Create Events
- [ ] Create database for Identity Schema
- [ ] Customize Identity Roles (Admin/User)
- [ ] Create Username option to Login
- [ ] Customize password strength
